version: '3'
services:
  qlf:
    image: felipelm/qlf
    environment:
      - QLF_API_URL=http://localhost:8000/dashboard/api
      - QLF_BASE_URL=http://localhost:8000
      - QLF_HOSTNAME=localhost
    volumes:
      - .:/app
    restart: always
    working_dir: /app/
    command: ./run.sh
    ports:
      - "8000:8000"
      - "5006:5006"
      - "56005:56005"
    links:
      - redis
  redis:
    image: redis
    ports:
      - "6379"