version: '3'
services:
  qlf:
    image: felipelm/qlf
    volumes:
      - .:/app
    restart: always
    working_dir: /app/
    command: ./run.sh
    ports:
      - "8000:8000"
      - "5006:5006"
      - "56005:56005"